---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-network-intel-com-v1alpha1-networkconfiguration
  failurePolicy: Fail
  name: mnetworkconfiguration.kb.io
  rules:
  - apiGroups:
    - network.intel.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkconfigurations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-network-intel-com-v1alpha1-networkconfiguration
  failurePolicy: Fail
  name: mnetworkconfiguration-v1alpha1.kb.io
  rules:
  - apiGroups:
    - network.intel.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkconfigurations
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-network-intel-com-v1alpha1-networkconfiguration
  failurePolicy: Fail
  name: vnetworkconfiguration.kb.io
  rules:
  - apiGroups:
    - network.intel.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkconfigurations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-network-intel-com-v1alpha1-networkconfiguration
  failurePolicy: Fail
  name: vnetworkconfiguration-v1alpha1.kb.io
  rules:
  - apiGroups:
    - network.intel.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkconfigurations
  sideEffects: None
