apiVersion: intel.com/v1alpha1
kind: NetworkClusterPolicy
metadata:
  name: netconf-gaudi-scale-out-l2
spec:
  configurationType: gaudi-so
  gaudiScaleOut:
    layer: L2
    image: intel/intel-network-linkdiscovery:1.0.0
    pullPolicy: IfNotPresent
  logLevel: 1
  nodeSelector:
    intel.feature.node.kubernetes.io/gaudi-ready: "true"
