# permissions for end users to view networkconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: intel-kubernetes-network-operator
    app.kubernetes.io/managed-by: kustomize
  name: networkconfiguration-viewer-role
rules:
- apiGroups:
  - network.intel.com
  resources:
  - networkconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.intel.com
  resources:
  - networkconfigurations/status
  verbs:
  - get
