apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linkdiscovery-openshift-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: linkdiscovery-sa
  namespace: tobechangedincontroller
