# permissions for end users to view networkclusterpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
  name: networkclusterpolicy-viewer-role
rules:
- apiGroups:
  - intel.com
  resources:
  - networkclusterpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - intel.com
  resources:
  - networkclusterpolicies/status
  verbs:
  - get
