# permissions for end users to edit networkconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
  name: networkconfiguration-editor-role
rules:
- apiGroups:
  - network.intel.com
  resources:
  - networkconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.intel.com
  resources:
  - networkconfigurations/status
  verbs:
  - get
