apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-network-tools
  labels:
    app: intel-network-tools
spec:
  selector:
    matchLabels:
      app: intel-network-tools
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: intel-network-tools
    spec:
      hostNetwork: true
      volumes:
      - name: nfd-features
        hostPath:
          path: /etc/kubernetes/node-feature-discovery/features.d/
          type: DirectoryOrCreate
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: intel/intel-network-linkdiscovery:latest
        imagePullPolicy: IfNotPresent
        name: configurator
        resources:
          limits:
            cpu: 100m
            memory: 90Mi
          requests:
            cpu: 40m
            memory: 45Mi
        volumeMounts:
        - mountPath: /etc/kubernetes/node-feature-discovery/features.d/
          name: nfd-features
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
            add:
              - NET_ADMIN
              - NET_RAW
      terminationGracePeriodSeconds: 10
